-- ============================================================
-- Barangay File Manager - Database Schema
-- Run this script once to set up the database.
-- ============================================================

-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS barangay_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE barangay_db;

-- ------------------------------------------------------------
-- Table: users
-- Stores both Admin and Resident accounts.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    full_name   VARCHAR(150)    NOT NULL,
    email       VARCHAR(150)    NOT NULL UNIQUE,
    password    VARCHAR(255)    NOT NULL,   -- stored as bcrypt hash
    role        ENUM('admin', 'resident') NOT NULL DEFAULT 'resident',
    phone       VARCHAR(20),                -- used for mock SMS
    address     VARCHAR(255),
    created_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Table: document_requests
-- Tracks every document request from submission to claiming.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS document_requests (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    resident_id     INT             NOT NULL,
    document_type   VARCHAR(100)    NOT NULL,
    purpose         TEXT,           -- why the resident needs the document
    status          ENUM(
                        'Submitted',
                        'Under Review',
                        'Approved (Ready for Pickup)',
                        'Claimed'
                    ) NOT NULL DEFAULT 'Submitted',
    pickup_date     DATE,           -- set by admin on approval
    pickup_time     TIME,           -- set by admin on approval
    admin_notes     TEXT,           -- internal notes visible to admin only
    created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP
                                            ON UPDATE CURRENT_TIMESTAMP,

    -- Foreign key to users table
    CONSTRAINT fk_request_resident
        FOREIGN KEY (resident_id) REFERENCES users(id)
        ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- Table: messages
-- Simple message log attached to each document request.
-- Both admin and resident can post messages.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    request_id  INT         NOT NULL,
    sender_id   INT         NOT NULL,
    sender_role ENUM('admin', 'resident') NOT NULL,
    body        TEXT        NOT NULL,
    created_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_msg_request
        FOREIGN KEY (request_id) REFERENCES document_requests(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_msg_sender
        FOREIGN KEY (sender_id) REFERENCES users(id)
        ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- Seed Data: default admin account
-- Password is "admin123" (bcrypt hash generated by the app)
-- You can change the credentials after first login.
-- ------------------------------------------------------------
INSERT IGNORE INTO users (full_name, email, password, role, phone)
VALUES (
    'Barangay Secretary',
    'admin@barangay.gov.ph',
    -- bcrypt hash of "admin123" (cost factor 12)
    '$2b$12$KIXkQ8V7MqNl/sHl1mP7wuF1eLvK9ZMv8nmYRpO3bBq0Q4XkXvRRi',
    'admin',
    '09001234567'
);
